version: 2
updates:
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "weekly"

  - package-ecosystem: "pip"
    directory: "/apps/agents/base-adk-agent"
    schedule:
      interval: "weekly"

  - package-ecosystem: "pip"
    directory: "/apps/agents/a2a-agent"
    schedule:
      interval: "weekly"

  - package-ecosystem: "pip"
    directory: "/apps/services/corporate-email"
    schedule:
      interval: "weekly"

  - package-ecosystem: "pip"
    directory: "/apps/services/income-verification"
    schedule:
      interval: "weekly"

  - package-ecosystem: "pip"
    directory: "/apps/services/legacy-dms"
    schedule:
      interval: "weekly"
